"""Add 2FA fields to User

Revision ID: 16c66216599b
Revises: 2ac5a36b12e4
Create Date: 2025-03-13 05:46:45.533954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c66216599b'
down_revision = '2ac5a36b12e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('activation_2fa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('activation_2fa_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_2fa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('login_2fa_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_2fa_expiry')
        batch_op.drop_column('login_2fa_code')
        batch_op.drop_column('activation_2fa_expiry')
        batch_op.drop_column('activation_2fa_code')
        batch_op.drop_column('two_fa_enabled')

    # ### end Alembic commands ###
