"""Add server defaults import

Revision ID: 662dbace13ce
Revises: 16c66216599b
Create Date: 2025-03-13 05:52:51.131891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662dbace13ce'
down_revision = '16c66216599b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('activation_2fa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('activation_2fa_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_2fa_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('login_2fa_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_2fa_expiry')
        batch_op.drop_column('login_2fa_code')
        batch_op.drop_column('activation_2fa_expiry')
        batch_op.drop_column('activation_2fa_code')
        batch_op.drop_column('two_fa_enabled')

    # ### end Alembic commands ###
